Added an array with 3 objects, use the map function to iterate over i…
Code-the-Dream-School/ctd-react-albatross pull request #7
Opened 2022-06-14 01:16 UTC by Karla1981

…t and return list item

2022-06-14 01:21 UTC, Karla1981 commented
Lesson-1-1

2022-06-27 12:06 UTC, obrienwritescode commented
Hello @Karla1981, this PR is within the Code-the-Dream-School Github organization.  Could you please fork the ctd-react-albatross repository and then create PRs within it.  Instructions can be found here: https://github.com/Code-the-Dream-School/ctd-react-albatross/wiki/General-Instructions#project-setup

2022-06-27 12:30 UTC, obrienwritescode commented on src/App.js
> +            return <li>{listItem.id} {listItem.title}</li>;
Your <li> is missing one required attribute that should be present.  Take a closer look at the assignment and see if you can find that attribute.

2022-06-27 12:32 UTC, obrienwritescode requested changes
- Fork the CTD repository into your own and then always merge into your own repository. 
- Verify the missing attribute for `<li>` elements.

2022-06-27 18:42 UTC, closed without merging